---
- name: Firewall changes
  hosts: all
  become: true

  tasks:
  - name: Enable a service in firewalldd
    firewalld:
      port: 80/tcp
      permanent: true
      state: disabled
    notify: 
      - Reload firewalld

  handlers:
  - name: Reload firewalld
    service:
      name: firewalld
      state: reloaded

'''
This playbook configures firewall settings on remote hosts.

Key Components:
Task:
Enable a Service in Firewalld:

Disables the 80/tcp port in the firewalld configuration.
Makes the change permanent using permanent: true.
Notifies the handler to reload the firewalld service after the change.
Handler:
Reload Firewalld:

Reloads the firewalld service to apply the changes.
'''
