---
- name: Installing Httpd
  hosts: all

  tasks:
  - name: Install httpd on Redhat
    yum:
      name: httpd
      state: present
    when: ansible_os_family == "RedHat"

  - name: Install apache2 on Ubuntu
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Ubuntu"

'''
This playbook installs the appropriate web server (httpd or apache2) based on the operating system of the remote hosts.

Key Components:
Tasks:
Install httpd on RedHat:
Installs the httpd package on RedHat-based systems (e.g., CentOS, RHEL).
The task runs only when the OS is RedHat.
Install apache2 on Ubuntu:
Installs the apache2 package on Ubuntu-based systems.
The task runs only when the OS is Ubuntu.
'''
